### ISSUE TITLE
Scheduler not running after migrating from v10->v11

### ISSUE THREAD

**Issue by paulator** [Monogramm/docker-erpnext#21] opened 2019-10-15 12:04 UTC
I started with v10, restored the backup and started ERPNext. Everything worked as expected.
After migrating to v11, I got the error message in the ERPNext frontend as depicted here:

**How To Reproduce**
Start with v10 images, 
```
docker-compose up -d
docker-compose down
docker-compose run --rm erpnext_app bench --force restore \
--with-public-files  /home/frappe/frappe-bench/sites/my.site/private/backups/my_site-files.tar \
--with-private-files /home/frappe/frappe-bench/sites/my.site/private/backups/my_site-private-files.tar \
                     /home/frappe/frappe-bench/sites/my.site/private/backups/my_site-database.sql.gz
docker-compose up
```
check, if everything was restored as expected
update docker-compose.yaml to v11
`docker-compose up -d`

After migration, i got the shown error message

**Expected behavior**
I would like to have the scheduler running.
If i fire the following command, the scheduler is up and running again:

`docker-compose run --rm erpnext_app bench --site all enable-scheduler`
**Screenshots**
![image](https://user-images.githubusercontent.com/7262648/66829466-b9339400-ef53-11e9-88b9-ddab977749e4.png)

**Docker (please complete the following information):**
 - Docker / Docker-compose Version:  Docker Version: 19.03.2, docker-compose version 1.24.1, build 4667896
 - Images: 
monogramm/docker-erpnext   11-alpine
monogramm/docker-erpnext   10-alpine

**Desktop (please complete the following information):**
 - OS: debian10
 - Browser safari
 - Version 13.02

**Smartphone (please complete the following information):**

**Additional context**

**Comment by madmath03** [comment] 2019-10-16 10:23
Hello @paulator ,

Thank you for reporting this.
It's very possible that the issue is more related to the ERPNext migration itself than this docker container, but I will try to help you find out the root cause.

First thing that comes to my mind might be a silly question, but better safe than sorry: when you updated the `docker-compose.yml`,  you updated all the containers version and not just the `erpnext_app`, right ? I'm not sure how ERPNext would behave if the app is in v11 but the schedulers in v10.

Next, is it possible for you to share the logs of the containers with `docker-compose logs` ?
If the scheduler is not running, I'm expecting to see an error message in the docker logs explaining the reason why it crashed.

Looking forward to your answer.

**Comment by paulator** [comment] 2019-10-21 17:05
Regarding your questions:

Yes, all images are at the same version. 

After resetting my complete test, I started with a blank v10 image / database and started the system with docker-compose up. In the logfile I found the following message from erpnext_app at the end of the initialization:

`[app] [2019-10-21T18:58:24] Apps python packages installed
 [app] [2019-10-21T18:58:24] Setup logs folders and files owner to frappe...
 [app] [2019-10-21T18:58:24] Checking diagnostic info...
 -----Checking scheduler status-----
 Scheduler disabled for my.site
 Workers online: 0
 -----None Jobs-----
 [app] [2019-10-21T18:58:32] Everything seems to be good with your Frappe environment and background workers.
 [app] [2019-10-21T18:58:32] Starting app on port 8000...`

from the scheduler I got the following logs:
`[scheduler] [2019-10-21T18:58:17] Waiting apps...
 [scheduler] [2019-10-21T18:58:27] Waiting for docker container init...
 [scheduler] [2019-10-21T18:58:27] Waiting for frappe current site to be set...
 [scheduler] [2019-10-21T18:58:27] Starting scheduler...`

**Comment by paulator** [comment] 2019-10-21 17:06
e

**Comment by paulator** [comment] 2019-10-21 17:09
One more information: with the command 
`docker-compose run --rm erpnext_app bench --site all enable-scheduler`
I'm able to start the scheduler...

**Comment by madmath03** [comment] 2019-10-24 19:48
Hello @paulator ,

Thank you for your answers.
We have been trying to reproduce this issue with the steps you provided without any success so far, but (luckily) we've had a test environment this week that had the exact same behavior.

We are currently testing a fix that should enable schedulers automatically after a successful `bench doctor` and call it after backup, restore and migrate.

We will let you know as soon as the fix as been deployed to the docker containers.

**Comment by madmath03** [comment] 2019-10-26 07:46
I will reopen this until we can add enhancements for the _custom_ restore function that allow to set the private and public files and automatically execute bench doctor and enable schedulers.

**Comment by paulator** [comment] 2019-10-28 18:19
I can confirm: With the current updated images, the scheduler is started as expected.

**Comment by madmath03** [comment] 2019-11-12 17:08
Hello @paulator,

The `restore` function in the `docker-frappe`  has been improved to accept to set the full path of the SQL, private and public files, so everything should be good now:
```
docker-compose run --rm erpnext_app bench restore /path/to/backup.sql /path/to/public.zip /path/to/private.zip
```

I'm closing this issue but feel free to report any new issues you may find.

**Closed by madmath03** 2019-11-12 17:08 UTC
Labels: bug
